//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSC2019.Model
{
    using System;
    
    public partial class SP_GetdgvRequest_Result2
    {
        public string AssetSN { get; set; }
        public string AssetName { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string EmployeeFullName { get; set; }
        public string Department { get; set; }
        public string AssetID { get; set; }
        public int EmergencyMaintenanceID { get; set; }
        public string EmployeeID { get; set; }
        public string DepartmentLocationID { get; set; }
        public string DepartmentID { get; set; }
        public string PriorityID { get; set; }
    }
}
